name: 'Squared Number'
description: 'Calculate the square of a number'
inputs:
  number:
    description: 'A number being squared'
    required: True
  testing_var:
    description: 'Nothing'
    default: ""
outputs:
  squared-number:
    description: 'A squared number'
    value: ${{ steps.calculation.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Calculation
      id: calculation
      run: |
        if [ -n "${{ inputs.testing_var }}" ]; then
          ANS=$(( ${{inputs.number}} * ${{inputs.number}} ))
          echo "result=$ANS" >> $GITHUB_OUTPUT
        else
          ANS="Nothing"
          echo "result=$ANS" >> $GITHUB_OUTPUT
        fi
      shell: bash

