name: Test environment

on:
  workflow_dispatch:

jobs:
  dev:
    strategy:
      matrix:
        call_actions: [a,b]
    uses: ./.github/workflows/call_${{ matrix.call_actions }}.yml
    with: 
      appname: ${{ matrix.call_actions }}