name: Test environment

on:
  workflow_dispatch:

jobs:
  dev:
    uses: ./.github/workflows/call_apply.yml
    with: 
      appname: ${{ matrix.call_actions }}
    secrets: &secrets_template
      env_vars: |
        SEC1=A
        SEC2=B

  sit:
    uses: ./.github/workflows/call_apply.yml
    with: 
      appname: ${{ matrix.call_actions }}
    secrets: 
      <<: *secrets_template
      env_vars: |
        SEC1=C