name: Test syntax
on: 
    workflow_dispatch:
      inputs:
        executor:
          description: 'Enter a number to calculate square'
          required: True
          type: choice
          options:
            - bash
            - python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export environment variables (Bash)
        if: ${{ inputs.executor == 'bash' }}
        shell: bash
        env:
          env_vars: |
            APP_NAME=my-app
            APP_ENV=preprod
            API_KEY=secret123
            DB_PASSWORD=abc456
        run: |
          while read -r i; do
            echo "::add-mask::${i#*=}"
            printf '%s\n' "$i" >> "$GITHUB_ENV"
          done <<< "$env_vars"


      - name: Export environment variables (Python)
        if: ${{ inputs.executor == 'python' }}
        env:
          env_vars: |
            APP_NAME=my-app
            APP_ENV=preprod
            API_KEY=secret123
            DB_PASSWORD=abc456
        run: |
          python .github/scripts/export-env-vars.py
          echo "APP_NAME=$APP_NAME"
          echo "APP_ENV=$APP_ENV"
          echo "API_KEY=$API_KEY"
          echo "DB_PASSWORD=$DB_PASSWORD"

      